"""initial

Revision ID: e647ad0c8de8
Revises:
Create Date: 2026-04-05 21:04:23.687044

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e647ad0c8de8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stock_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stock_items_id"))
        batch_op.drop_index(batch_op.f("ix_stock_items_name"))

    op.drop_table("stock_items")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_items",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("quantity", sa.INTEGER(), nullable=False),
        sa.Column("unit", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stock_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_stock_items_name"), ["name"], unique=1)
        batch_op.create_index(batch_op.f("ix_stock_items_id"), ["id"], unique=False)

    # ### end Alembic commands ###
